swagger2:
  port: ${server.port}
  api:
    title: YZC-AUTH
    description: 权限服务
    contact:
      name: xxx
      url: xxx
      email: xxx
    version: 1.0.0
  base-api-packages:
    - com.vy.yzc.auth.server.interfaces.facade
