server:
  port: 13000
spring:
  profiles:
    active: SIT
    include: Swagger2, OAuth2
  application:
    name: yzc-auth
  main:
    allow-bean-definition-overriding: true
  jackson:
    default-property-inclusion: NON_NULL
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-2ze24207w07l455998o.mysql.rds.aliyuncs.com/yzc_sit?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: visva
    password: WmaiVisva2018
    hikari:
      # 一个连接idle状态的最大时长（毫秒），超时则被释放（retired），缺省:10分钟
      idle-timeout: 600000
      # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQLException， 缺省:30秒
      connection-timeout: 30000
      # 一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒
      max-lifetime: 1800000
      maximum-pool-size: 100
      minimum-idle: 30
      pool-name: HikariConnectionPool
  redis:
    database: 11
    host: visva-sit.redis.rds.aliyuncs.com
#    host: r-2zee54f9c0c25de4.redis.rds.aliyuncs.com
    port: 6379
    password: WmaiVisva2018
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: 2ms
    timeout: 5000ms

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:8002/eureka
      #Eureka客户端向服务端发送心跳的时间间隔，单位为秒（客户端告诉服务端自己会按照该规则）
      #租约续订间隔时间（默认30秒），如下所示每间隔 5s 向服务端发送一次心跳，证明自己依然"存活"
      lease-renewal-interval-in-seconds: 3 # 5秒一次心跳
      #Eureka服务端在收到最后一次心跳之后等待的时间上限，单位为秒，超过则剔除（客户端告诉服务端按照此规则等待自己）
      # 租约到期时间（默认90秒），如下所示，告诉服务端如果我 6s 之内没有给你发心跳，就代表我"死"了，将我踢出掉
      lease-expiration-duration-in-seconds: 6

management:
  endpoints:
    web:
      exposure:
        include: "threaddump,heapdump,health,info,service-registry,shutdown"
  endpoint:
    health:
      show-details: ALWAYS
    shutdown:
      enabled: true
logging:
  config: classpath:log4j2.yml

ribbon:
  ReadTimeout: 2000000
  ConnectTimeout: 2000000
  eureka:
    enabled: true
  # 同一实例最大重试次数，不包括首次调用
  MaxAutoRetries: 1
  # 重试其他实例的最大重试次数，不包括首次所选的server
  MaxAutoRetriesNextServer: 2
  # 是否所有操作都进行重试
  #OkToRetryOnAllOperations: true

# Hystrix线程池核心线程数
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
      # 设置进入熔断器的阈值个数
      circuitBreaker:
        requestVolumeThreshold: 1000
      # 最大回退个数
      fallback:
        isolation:
          semaphore:
            maxConcurrentRequests: 50
  threadpool:
    default:
      coreSize: 500